### PR TITLE
Add signature to check for recently common CNI configuration error

### PR DESCRIPTION
**Pull request by omertuc**
A lot of recent production installation failures seem to be caused by an
error where kubelet complains about CNI plugin configuration.

This new signature looks for this repetitive error in the kubelet
journal of one of the control plane nodes, and if it finds it more
than threshold (1000) times, it creates the signature.

The journal logs are found in the installer-gather bootstrap log bundle,
under the control-plane masters-gather directory.

### CODE REVIEW

**Comment by osherdp** [comment]
@omertuc some PR description will be much appreciated

**Comment by omertuc** [comment]
Updates description

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
tested? can I push?

**Comment by omertuc** [comment]
Yep

**Comment by omertuc** [comment]
Might want to retroactively run this on previous tickets... not sure who's responsible for doing that

**Comment by osherdp** [comment]
it should run it on anything which still has logs

**Pull request merged**
