### PR TITLE
MGMT-12867 Add a signature to nsenter failures

### PR DESCRIPTION
**Pull request by filanov**
Not all nsemter command will cause the agnet to fail command execution, This signature will help to catch those cases

an example:

level=info msg=\"failed executing nsenter [--target 1 --cgroup --mount --ipc --pid -- mdadm --stop /dev/md127]

the level of this command is info and it will not cause the agnet to fail the step execution but it did cause an issue with the installation later

### CODE REVIEW

**Comment by filanov** [comment]
/hold
not sure how to test it

**Comment by omertuc** [comment]
> > not sure how to test it
> 
> `tools/add_triage_signature.py` can run this check in dry run mode against a particular triage issue (`-i`) or recent (30 days) (`-r`)

See `CONTRIBUTING.md` for more details on signature testing / development

**Comment by omertuc** [comment]
Yes I agree, this should not be "nsenter" specific. We use nsenter when we want to escape the container into the host's namespaces, but that's just an implementation detail that could theoretically change

**Comment by filanov** [comment]
My reference was https://issues.redhat.com/browse/AITRIAGE-4689 
Looking at the ticket again i can see that step signature does cover this case. 
looking at the existing signature i couldn't see the failure this is why it looked like it wasn't covered. 
Closing this PR

**Pull request closed without merging**
