### PR TITLE
fix all pep8 violations

### PR DESCRIPTION
**Pull request by osherdp**
Just going over the code to make it prettier (and make it pass the lint job).

### CODE REVIEW

**Comment by YuviGold** [comment]
What's this `dco`?

**Comment by osherdp** [comment]
> What's this `dco`?

won't be on next PRs
It's one of the plugins that I removed

**Comment by YuviGold** [comment]
> > What's this `dco`?
> 
> won't be on next PRs
> It's one of the plugins that I removed

Okay. In that case `tide` still blocking just override

**Pull request merged**
