### PR TITLE
StaticNetworking signature

### PR DESCRIPTION
**Pull request by omertuc**
See example https://issues.redhat.com/browse/AITRIAGE-3677?focusedCommentId=20715928&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20715928

### CODE REVIEW

**Comment by romfreiman** [comment]
Nice!
Can u differentiate  if the statics networking was done by the UI template or user injecting the yaml? I think it will make a lot of difference. Also, if we we'll be able to identify Jiras according to it would be very usefull IMO.

Any chance you can find missconfigrations? Unsupported fields? Identation problems?

**Comment by omertuc** [comment]
>Nice!
Can u differentiate if the statics networking was done by the UI template or user injecting the yaml? I think it will make a lot of difference. Also, if we we'll be able to identify Jiras according to it would be very usefull IMO.
Any chance you can find missconfigrations? Unsupported fields? Identation problems?

Would love to do all that in a separate PR. For now it's already useful in its current form so let's merge if there are no issues

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by eranco74** [comment]
> Nice! Can u differentiate if the statics networking was done by the UI template or user injecting the yaml? I think it will make a lot of difference. Also, if we we'll be able to identify Jiras according to it would be very usefull IMO.
> 
> Any chance you can find missconfigrations? Unsupported fields? Identation problems?

We can already identify Jiras according static-network-config
https://issues.redhat.com/issues/?jql=labels%20%3D%20FEATURE-Static-Network-Config

**Pull request merged**
