### PR TITLE
sno cannot have etcd in hostname

### PR DESCRIPTION
**Pull request by omertuc**
See https://issues.redhat.com/issues/?jql=project%20in%20(12325045%2C%2012327120)%20AND%20cf%5B12317358%5D%20%3D%20SIGNATURE_etcd_in_sno_hostname

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by omertuc** [comment]
forced push for lint

**Pull request merged**
