### PR TITLE
NO-ISSUE: Don't assign auto-closed tickets to a human

### PR DESCRIPTION
**Pull request by mkowalski**
/cc @adriengentil 
/cc @omertuc

### CODE REVIEW

**Comment by omertuc** [comment]
Leacing

**Comment by omertuc** [comment]
Leaving behind commented out code is unnecessary, we can always just revert this commit if we ever want it back

**Comment by omertuc** [comment]
Sorry closed due to misclick

**Comment by mkowalski** [comment]
Totally agree, just fixed and completely removed that

**Pull request merged**
