### PR TITLE
MGMT-15569 - build script for move to appSRE

### PR DESCRIPTION
**Pull request by eifrach**
* Creating build script for migration to appSRE
* adding backward compatibility for the migration phase

### CODE REVIEW

**Comment by eifrach** [comment]
> wait, didn't we talk about onboarding assisted-installer-cicd repo to appsre?
yes, so we are going to do it in 2 phases
1.  move all app's to appsre 
2.  move the repo / code to a assisted-installer-cicd 

after all moved to appsre moving the code will be much simpler, The code will also need some work/cleanup during the  move

**Comment by osherdp** [comment]
> > wait, didn't we talk about onboarding assisted-installer-cicd repo to appsre?
> > yes, so we are going to do it in 2 phases
> 
> 1. move all app's to appsre
> 2. move the repo / code to a assisted-installer-cicd
> 
> after all moved to appsre moving the code will be much simpler, The code will also need some work/cleanup during the move

@rccrdpccl wdyt?
it seems to me like a total redundancy of components to introduce in app-interface

**Comment by rccrdpccl** [comment]
> @rccrdpccl wdyt?
> it seems to me like a total redundancy of components to introduce in app-interface

What are we trying to achieve?
A lot of components of this repo are already migrated to assisted-installer-cicd

**Comment by rccrdpccl** [comment]
@eifrach I think we can close this, right?

**Comment by eifrach** [comment]
I will need it - but its already too old so i will recreate it

/close

**Pull request closed without merging**
